// # Barrel export for overlay components
export { LowerThird } from './LowerThird'
export type { LowerThirdProps } from './LowerThird'
export { FilmGrain } from './FilmGrain'
export type { FilmGrainProps } from './FilmGrain'
export { Watermark } from './Watermark'
export type { WatermarkProps } from './Watermark'
export { FootageBackground } from './FootageBackground'
export type { FootageBackgroundProps } from './FootageBackground'
export { Vignette } from './Vignette'
export type { VignetteProps } from './Vignette'
export { Particles } from './Particles'
export type { ParticlesProps } from './Particles'
export { Letterbox } from './Letterbox'
export type { LetterboxProps } from './Letterbox'
